// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Channel struct {
	ID          string
	ServerId    string
	ChannelName string
	Type        string
}

type Server struct {
	ID        string
	Name      string
	CreatedBy sql.NullString
}

type User struct {
	ID              string
	Email           string
	Username        string
	Password        string
	ProfilePricture sql.NullString
}

type UserServer struct {
	UserId   string
	ServerId string
}
