// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Channel struct {
	ID          string
	ServerId    string
	ChannelName string
	Type        string
}

type Friend struct {
	UserID string
	Friend string
	Status int16
}

type RefreshToken struct {
	ID        uuid.UUID
	UserId    string
	CreatedAt int64
	ExpiresAt int64
	Token     string
}

type Server struct {
	ID        string
	Name      string
	CreatedBy string
	Picture   sql.NullString
}

type User struct {
	ID              string
	Email           string
	Username        string
	Password        string
	ProfilePricture sql.NullString
}

type UserServer struct {
	UserId   string
	ServerId string
}
