// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addUserToServer = `-- name: AddUserToServer :exec
INSERT INTO public."userServers"(
	"userId", "serverId")
	VALUES ($1, $2)
`

type AddUserToServerParams struct {
	UserId   string
	ServerId string
}

func (q *Queries) AddUserToServer(ctx context.Context, arg AddUserToServerParams) error {
	_, err := q.db.ExecContext(ctx, addUserToServer, arg.UserId, arg.ServerId)
	return err
}

const countUserServerByUserId = `-- name: CountUserServerByUserId :one
SELECT COUNT("userId") as "userServer"
	FROM public."userServers" WHERE "userId" = $1 AND "serverId" = $2
`

type CountUserServerByUserIdParams struct {
	UserId   string
	ServerId string
}

func (q *Queries) CountUserServerByUserId(ctx context.Context, arg CountUserServerByUserIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserServerByUserId, arg.UserId, arg.ServerId)
	var userServer int64
	err := row.Scan(&userServer)
	return userServer, err
}

const createChannel = `-- name: CreateChannel :exec
INSERT INTO public.channels(
	id, "serverId", "channelName", type)
	VALUES ($1, $2, $3, $4)
`

type CreateChannelParams struct {
	ID          string
	ServerId    string
	ChannelName string
	Type        string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.ID,
		arg.ServerId,
		arg.ChannelName,
		arg.Type,
	)
	return err
}

const createServer = `-- name: CreateServer :exec
INSERT INTO public.servers(
	id, name, "createdBy", picture)
	VALUES ($1, $2, $3, $4)
`

type CreateServerParams struct {
	ID        string
	Name      string
	CreatedBy string
	Picture   sql.NullString
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer,
		arg.ID,
		arg.Name,
		arg.CreatedBy,
		arg.Picture,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO public.users(
	id, email, username, password)
	VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID       string
	Email    string
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	return err
}

const getServerChannels = `-- name: GetServerChannels :many
SELECT id, "serverId", "channelName", type
	FROM public.channels WHERE "serverId" = $1
`

func (q *Queries) GetServerChannels(ctx context.Context, serverid string) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getServerChannels, serverid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ServerId,
			&i.ChannelName,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, "profilePricture"
	FROM public.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.ProfilePricture,
	)
	return i, err
}

const getUserJoinedServers = `-- name: GetUserJoinedServers :many
SELECT "servers".id, "servers".name, "servers".picture from "userServers" LEFT JOIN
public."servers" ON "userServers"."serverId" = "servers"."id"
WHERE "userServers"."userId" = $1
`

type GetUserJoinedServersRow struct {
	ID      sql.NullString
	Name    sql.NullString
	Picture sql.NullString
}

func (q *Queries) GetUserJoinedServers(ctx context.Context, userid string) ([]GetUserJoinedServersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserJoinedServers, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserJoinedServersRow
	for rows.Next() {
		var i GetUserJoinedServersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Picture); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO public."refreshTokens"(
	id, "userId", "createdAt", "expiresAt", token)
	VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	UserId    string
	CreatedAt int64
	ExpiresAt int64
	Token     string
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.UserId,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Token,
	)
	return err
}

const test = `-- name: Test :exec

SELECT 1
`

// db/query.sql
func (q *Queries) Test(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, test)
	return err
}
